apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{.Values.podSecurityPolicyName}}
  namespace: {{.Values.namespace}}
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - '*'