apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: matomo-tracker
  name: matomo-tracker
  namespace: {{.Values.namespace}}
spec:
  rules:
  - host: {{.Values.matomo.tracker.hostname}}
    http:
      paths:
      - backend:
          serviceName: matomo-tracker
          servicePort: 8080
        path: /piwik.php
      - backend:
          serviceName: matomo-tracker
          servicePort: 8080
        path: /piwik.js
