apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo-configuration
  namespace: {{.Values.namespace}}
data:
  install.json: |
    {
      "PluginsInstalled": [
        "Diagnostics",
        "DBStats",
        "Login",
        "CoreAdminHome",
        "UsersManager",
        "SitesManager",
        "Installation",
        "Monolog",
        "Intl",
        "CorePluginsAdmin",
        "CoreHome",
        "WebsiteMeasurable",
        "CoreVisualizations",
        "Proxy",
        "API",
        "Transitions",
        "Actions",
        "Referrers",
        "UserLanguage",
        "DevicesDetection",
        "Goals",
        "SEO",
        "Events",
        "UserCountry",
        "GeoIp2",
        "VisitsSummary",
        "VisitFrequency",
        "VisitTime",
        "VisitorInterest",
        "CoreUpdater",
        "CoreConsole",
        "UserCountryMap",
        "Live",
        "ImageGraph",
        "Annotations",
        "Insights",
        "Morpheus",
        "Contents",
        "DevicePlugins",
        "UserId",
        "CustomPiwikJs",
        "ExtraTools",
        "LanguagesManager",
        "SegmentEditor",
        "Dashboard",
        "ScheduledReports",
        "PrivacyManager",
        "CustomVariables",
        "IntranetMeasurable",
        "ExamplePlugin",
        "Widgetize",
        "MultiSites",
        "Ecommerce",
        "ExampleAPI",
        "RssWidget",
        "Feedback",
        "TwoFactorAuth",
        "MobileMessaging",
        "Overlay",
        "TestRunner",
        "BulkTracking",
        "Resolution",
        "Heartbeat",
        "Marketplace",
        "ProfessionalServices",
        "QueuedTracking"
      ],
      "Site": {
        "name": "Localhost",
        "url": "http://localhost:8080"
      },
      "Config": {
          "General": {
              "session_save_handler": "dbtable",
              "enable_trusted_host_check": 0
          },
          "QueuedTracking": {
            "useSentinelBackend": 1,
            "sentinelMasterName": "redisMaster",
            "redisHost": "matomo-redis-redis-ha-announce-0",
            "redisPort": "26379",
            "redisDatabase": "0",
            "redisPassword": 0,
            "queueEnabled": 1,
            "numQueueWorkers": 1,
            "numRequestsToProcess": "25",
            "processDuringTrackingRequest": 1
          }
      }
    }