apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo-phpfpm
  namespace: {{.Values.namespace}}
{{- if .Values.matomo.phpfpm }}
data:
  zz-global.conf: |
    [www]
    pm.max_children = {{ .Values.matomo.phpfpm.max_children | default 100 }}
    pm.start_servers =  {{ .Values.matomo.phpfpm.start_servers | default 25 }}
    pm.min_spare_servers =  {{ .Values.matomo.phpfpm.min_spare_servers | default 25 }}
    pm.max_spare_servers =  {{ .Values.matomo.phpfpm.max_spare_servers | default 75 }}
    pm.max_requests =  {{ .Values.matomo.phpfpm.max_requests | default 100 }}
    pm.process_idle_timeout = {{ .Values.matomo.phpfpm.process_idle_timeout | default "30s" }}
{{ else }}
data:
  zz-global.conf: |
    [www]
    pm.max_children = 100
    pm.start_servers = 25
    pm.min_spare_servers = 25
    pm.max_spare_servers = 75
    pm.max_requests =  100
    pm.process_idle_timeout = "30s"
{{- end }}