apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo-configuration
  namespace: {{.Values.namespace}}
data:
  install.json: |
    {
      "PluginsInstalled": [
        "Diagnostics",
        "DBStats",
        "Login",
        "CoreAdminHome",
        "UsersManager",
        "SitesManager",
        "Installation",
        "Monolog",
        "Intl",
        "CorePluginsAdmin",
        "CoreHome",
        "WebsiteMeasurable",
        "CoreVisualizations",
        "Proxy",
        "API",
        "Transitions",
        "Actions",
        "Referrers",
        "UserLanguage",
        "DevicesDetection",
        "Goals",
        "SEO",
        "Events",
        "UserCountry",
        "GeoIp2",
        "VisitsSummary",
        "VisitFrequency",
        "VisitTime",
        "VisitorInterest",
        "CoreUpdater",
        "CoreConsole",
        "UserCountryMap",
        "Live",
        "ImageGraph",
        "Annotations",
        "Insights",
        "Morpheus",
        "Contents",
        "DevicePlugins",
        "UserId",
        "CustomPiwikJs",
        "ExtraTools",
        "LanguagesManager",
        "SegmentEditor",
        "Dashboard",
        "ScheduledReports",
        "PrivacyManager",
        "CustomVariables",
        "IntranetMeasurable",
        "ExamplePlugin",
        "Widgetize",
        "MultiSites",
        "Ecommerce",
        "ExampleAPI",
        "RssWidget",
        "Feedback",
        "TwoFactorAuth",
        "MobileMessaging",
        "Overlay",
        "TestRunner",
        "BulkTracking",
        "Resolution",
        "Heartbeat",
        "Marketplace",
        "ProfessionalServices",
        "QueuedTracking",
        "UserConsole"
      ],
      "Site": {
        "name": "Localhost",
        "url": "http://localhost"
      },
      "Config": {
        "log": {
          "log_level": "ERROR"
        },
        "General": {
          "noreply_email_address": "noreply@example.com",
          "enable_framed_pages": 1,
          "enable_framed_settings": 1,
          "enable_trusted_host_check": 0,
          "enable_plugin_update_communication": 0,
          "enable_auto_update": 0,
          "enable_installer": 0,
          "enable_internet_features": 0,
          "enable_plugins_admin": 0,
          "enable_plugin_upload": 0,
          "enable_geolocation_admin": 0,
          "proxy_client_headers[]": "HTTP_X_FORWARDED_FOR",
          "browser_archiving_disabled_enforce": 1,
          "enable_browser_archiving_triggering": 0,
          "archiving_range_force_on_browser_request": 0,
          "enable_sql_optimize_queries": 0,
          "enabled_periods_UI": "day,week,month,year,range",
          "enabled_periods_API": "day,week,month,year,range",
          "session_save_handler": "dbtable",
          "enable_marketplace": 0,
          "enable_general_settings_admin": 0,
          "piwik_pro_ads_enabled": 0,
          "assume_secure_protocol": 1,
          "cors_domains[]": "*",
          "datatable_archiving_maximum_rows_referrers": 2000,
          "datatable_archiving_maximum_rows_subtable_referrers": 2000,
          "datatable_archiving_maximum_rows_actions": 2000,
          "datatable_archiving_maximum_rows_subtable_actions": 2000,
          "datatable_archiving_maximum_rows_events": 2000,
          "datatable_archiving_maximum_rows_subtable_events": 2000,
          "datatable_archiving_maximum_rows_custom_variables": 2000,
          "datatable_archiving_maximum_rows_subtable_custom_variables": 2000
        },
        "QueuedTracking": {
          "useSentinelBackend": 1,
          "sentinelMasterName": "redisMaster",
          "redisHost": "matomo-redis-redis-ha-announce-0,matomo-redis-redis-ha-announce-1,matomo-redis-redis-ha-announce-2",
          "redisPort": "26379,26379,26379",
          "redisDatabase": "0",
          "redisPassword": 0,
          "queueEnabled": 1,
          "numQueueWorkers": 1,
          "numRequestsToProcess": "25",
          "processDuringTrackingRequest": 0
        }
      }
    }