---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: matomo-jobs-corearchive
  namespace: {{.Values.namespace}}
spec:
  schedule: "45 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{.Values.matomo.cron.coreArchive.activeDeadlineSeconds}}
      template:
        spec:
          initContainers:
          - name: matomo-init
            image: {{.Values.matomo.image}}
            securityContext:
              runAsUser: {{.Values.matomo.runAsUser}}
            env:
            - name: MATOMO_ADMIN_PASSWORD
              value: {{.Values.matomo.adminPassword}}
            - name: MATOMO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matomo-db-mysql
                  key: mysql-root-password
            resources:
              requests:
                memory: "512Mi"
                cpu: "1"
              limits:
                memory: "1Gi"
                cpu: "2"
            command: [ 'sh' , '-c' , '{{.Values.matomo.installCommand}}' ]
            volumeMounts:
              - name: static-data
                mountPath: /var/www/html
              - name: matomo-configuration
                mountPath: /tmp/matomo/
                readOnly: true
          containers:
          - name: matomo-jobs-corearchive
            image: {{.Values.matomo.image}}
            securityContext:
              runAsUser: {{.Values.matomo.runAsUser}}
            command: [ 'sh' , '-c' , 'php /var/www/html/console core:archive --skip-idsites=4,8' ]
            env:
            - name: MARIADB_MATOMO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matomo-db-mysql
                  key: mysql-root-password
            volumeMounts:
              - name: static-data
                mountPath: /var/www/html
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: matomo-registry-secret
          volumes:
          - name: matomo-configuration
            configMap:
              name: matomo-configuration
          - name: static-data
            emptyDir: {}
