---
{{- if .Values.matomo.cronJobs.coreArchive.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: matomo-jobs-corearchive
  namespace: {{.Values.namespace}}
  {{- template "matomo.labels" .Values.matomo.cronJobs.coreArchive.labels }}
spec:
  schedule: {{quote .Values.matomo.cronJobs.coreArchive.schedule}}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{.Values.matomo.cronJobs.coreArchive.activeDeadlineSeconds}}
      template:
        spec:
          initContainers:
          - name: matomo-init
            image: {{.Values.matomo.image}}
            securityContext:
              runAsUser: {{.Values.matomo.runAsUser}}
            env:
            - name: MATOMO_FIRST_USER_NAME
              value: {{.Values.matomo.dashboard.firstuser.username}}
            - name: MATOMO_FIRST_USER_EMAIL
              value: {{.Values.matomo.dashboard.firstuser.email}}
            - name: MATOMO_FIRST_USER_PASSWORD
              value: {{.Values.matomo.dashboard.firstuser.password}}
            - name: MATOMO_DB_HOST
              value: {{.Values.db.hostname}}
            - name: MATOMO_DB_NAME
              value: {{.Values.db.name}}
            {{ if .Values.db.prefix }}
            - name: MATOMO_DB_PREFIX
              value: {{.Values.db.prefix}}
            {{ end }}
            - name: MATOMO_DB_USERNAME
              value: {{.Values.db.username}}
            - name: MATOMO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.password.secretKeyRef.name }}
                  key: {{ .Values.db.password.secretKeyRef.key }}
            resources:
              requests:
                memory: "128Mi"
                cpu: "500m"
              limits:
                memory: "512Mi"
                cpu: "700m"
            command: [ 'sh' , '-c' , 'rsync -crlOt --no-owner --no-group --no-perms /usr/src/matomo/ /var/www/html/ && {{.Values.matomo.installCommand}}' ]
            volumeMounts:
              - name: static-data
                mountPath: /var/www/html
              - name: matomo-configuration
                mountPath: /tmp/matomo/
                readOnly: true
          containers:
          - name: matomo-jobs-corearchive
            {{- /* To add indentation to the inline template,
            we need to use "include" instead of "template" */ -}}
            {{- include "matomo.labels" .Values.matomo.cronJobs.coreArchive.labels | nindent 10 }}
            image: {{.Values.matomo.image}}
            resources:
              requests:
                memory: "128Mi"
                cpu: "500m"
              limits:
                memory: "512Mi"
                cpu: "700m"
            securityContext:
              runAsUser: {{.Values.matomo.runAsUser}}
            command: [ 'sh' , '-c' , '{{.Values.matomo.cronJobs.coreArchive.command}}' ]
            env:
            - name: MARIADB_MATOMO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.password.secretKeyRef.name }}
                  key: {{ .Values.db.password.secretKeyRef.key }}
            volumeMounts:
              - name: static-data
                mountPath: /var/www/html
              - name: matomo-phpfpm
                mountPath: /usr/local/etc/php-fpm.d/zz-global.conf
                subPath: zz-global.conf 
              - name: matomo-dashboard-php
                mountPath: /usr/local/etc/php/conf.d/zz-global.ini
                subPath: zz-global.ini  
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: matomo-registry-secret
          volumes:
          - name: matomo-configuration
            configMap:
              name: matomo-configuration
          - name: static-data
            emptyDir: {}
          - name: matomo-phpfpm
            configMap:
              name: matomo-phpfpm
          - name: matomo-dashboard-php
            configMap:
              name: matomo-dashboard-php
{{- end -}}
