{{- if .Values.matomo.cronJobs.swiftDbBackup }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: matomo-jobs-backup-db
  namespace: {{.Values.namespace}}
spec:
  schedule: {{quote .Values.matomo.cronJobs.swiftDbBackup.schedule}}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      annotations:
        kubernetes.io/change-cause: {{.Values.changeCause}}
    spec:
      template:
        spec:
          containers:
          - name: backupdb
            image: {{.Values.matomo.cronJobs.swiftDbBackup.image}}
            command: ["sh", "-c", "/scripts/backupdb.sh"]
            env:
            - name: DB_HOSTNAME
              value: {{.Values.db.hostnameSlave}}
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.db.password.secretKeyRef.name}}
                  key: {{.Values.db.password.secretKeyRef.key}}
            - name: DB_NAME
              value: {{.Values.db.name}}
            - name: DB_BACKUP_NAME_PREFIX
              value: {{.Values.matomo.cronJobs.swiftDbBackup.namePrefix}}
            - name: DB_DELETE_BACKUP_AFTER
              value: {{quote .Values.matomo.cronJobs.swiftDbBackup.deleteBackupAfter}}
            - name: ST_AUTH_VERSION
              valueFrom:
                secretKeyRef:
                  name: {{.Values.matomo.cronJobs.swiftDbBackup.openStackSecret}}
                  key: ST_AUTH_VERSION
            - name: OS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{.Values.matomo.cronJobs.swiftDbBackup.openStackSecret}}
                  key: OS_USERNAME
            - name: OS_USER_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: {{.Values.matomo.cronJobs.swiftDbBackup.openStackSecret}}
                  key: OS_USER_DOMAIN_NAME
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.matomo.cronJobs.swiftDbBackup.openStackSecret}}
                  key: OS_PASSWORD
            - name: OS_PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: {{.Values.matomo.cronJobs.swiftDbBackup.openStackSecret}}
                  key: OS_PROJECT_NAME
            - name: OS_PROJECT_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: {{.Values.matomo.cronJobs.swiftDbBackup.openStackSecret}}
                  key: OS_PROJECT_DOMAIN_NAME
            - name: OS_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: {{.Values.matomo.cronJobs.swiftDbBackup.openStackSecret}}
                  key: OS_AUTH_URL
            - name: OS_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{.Values.matomo.cronJobs.swiftDbBackup.openStackSecret}}
                  key: OS_USER_ID
            - name: OS_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: {{.Values.matomo.cronJobs.swiftDbBackup.openStackSecret}}
                  key: OS_PROJECT_ID
            - name: OS_SWIFT_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: {{.Values.matomo.cronJobs.swiftDbBackup.openStackSecret}}
                  key: OS_SWIFT_CONTAINER
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: matomo-registry-secret
{{- end -}}