apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: matomo-tracker
  name: matomo-tracker
  namespace: {{.Values.namespace}}
spec:
  rules:
  - host: {{.Values.matomo.tracker.hostname}}
    http:
      port: 80
      paths:
      - backend:
          serviceName: matomo-tracker
          servicePort: 8080
        path: /piwik.php
      - backend:
          serviceName: matomo-tracker
          servicePort: 8080
        path: /piwik.js
      - backend:
          serviceName: matomo-tracker
          servicePort: 8080
        path: /matomo.php
      - backend:
          serviceName: matomo-tracker
          servicePort: 8080
        path: /matomo.js
      - backend:
          serviceName: matomo-tracker
          servicePort: 8080
        path: /js/*
  {{- if .Values.matomo.tracker.tls }}
  tls:
  - hosts:
    - {{.Values.matomo.tracker.hostname}}
    {{- if .Values.matomo.tracker.secretName }}
    secretName: {{.Values.matomo.tracker.secretName}}
    {{- end -}}
  {{- end -}}
