apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo-blackfire-php
  namespace: {{.Values.namespace}}
{{- if .Values.matomo.dashboard.blackfire }}
data:
  blackfire.ini: |
    extension={{ .Values.matomo.dashboard.blackfire.blackfire_so_file | default "blackfire.so" }}
    blackfire.agent_socket={{ .Values.matomo.dashboard.blackfire.blackfire_agent_socket | default "tcp://blackfire:8707" }}
    blackfire.apm_connect_at_startup={{ .Values.matomo.dashboard.blackfire.blackfire_apm_connect_at_startup | default "0" }}
{{ else }}
data:
  blackfire.ini: |
    extension=blackfire.so
    blackfire.agent_socket=tcp://blackfire:8707
    blackfire.apm_connect_at_startup=0
{{- end }}
blackfire.agent_socket=unix:///var/run/blackfire/agent.sock