---
{{- if .Values.matomo.cronJobs.scheduledTasks.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: matomo-jobs-scheduled-tasks
  namespace: {{.Values.namespace}}
  {{- template "matomo.labels" .Values.matomo.cronJobs.scheduledTasks.labels }}
spec:
  schedule: {{quote .Values.matomo.cronJobs.scheduledTasks.schedule}}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{.Values.matomo.cronJobs.scheduledTasks.activeDeadlineSeconds}}
      template:
        spec:
          initContainers:
          - name: matomo-init
            image: {{.Values.matomo.image}}
            securityContext:
              runAsUser: {{.Values.matomo.runAsUser}}
            env:
            - name: MATOMO_FIRST_USER_NAME
              value: {{.Values.matomo.dashboard.firstuser.username}}
            - name: MATOMO_FIRST_USER_EMAIL
              value: {{.Values.matomo.dashboard.firstuser.email}}
            - name: MATOMO_FIRST_USER_PASSWORD
              value: {{.Values.matomo.dashboard.firstuser.password}}
            - name: MATOMO_DB_HOST
              value: {{.Values.db.hostname}}
            - name: MATOMO_DB_NAME
              value: {{.Values.db.name}}
            {{ if .Values.db.prefix }}
            - name: MATOMO_DB_PREFIX
              value: {{.Values.db.prefix}}
            {{ end }}
            - name: MATOMO_DB_USERNAME
              value: {{.Values.db.username}}
            - name: MATOMO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.password.secretKeyRef.name }}
                  key: {{ .Values.db.password.secretKeyRef.key }}
            resources:
              requests:
                memory: {{ .Values.matomo.cronJobs.scheduledTasks.resources.requests.memory }}
                cpu: {{ .Values.matomo.cronJobs.scheduledTasks.resources.requests.cpu  }}
              limits:
                memory: {{ .Values.matomo.cronJobs.scheduledTasks.resources.limits.memory }}
                cpu: {{ .Values.matomo.cronJobs.scheduledTasks.resources.limits.cpu }}
            command: [ 'sh' , '-c' , 'rsync -crlOt --no-owner --no-group --no-perms /usr/src/matomo/ /var/www/html/ && {{.Values.matomo.installCommand}}' ]
            volumeMounts:
              - name: static-data
                mountPath: /var/www/html
              - name: matomo-configuration
                mountPath: /tmp/matomo/
                readOnly: true
          containers:
          - name: matomo-jobs-scheduledtasks
            image: {{.Values.matomo.image}}
            securityContext:
              runAsUser: {{.Values.matomo.runAsUser}}
            command: [ 'sh' , '-c' , {{quote .Values.matomo.cronJobs.scheduledTasks.command}} ]
            env:
            - name: MARIADB_MATOMO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.password.secretKeyRef.name }}
                  key: {{ .Values.db.password.secretKeyRef.key }}
            resources:
              requests:
                memory: {{ .Values.matomo.cronJobs.scheduledTasks.resources.requests.memory }}
                cpu: {{ .Values.matomo.cronJobs.scheduledTasks.resources.requests.cpu  }}
              limits:
                memory: {{ .Values.matomo.cronJobs.scheduledTasks.resources.limits.memory }}
                cpu: {{ .Values.matomo.cronJobs.scheduledTasks.resources.limits.cpu }}
            volumeMounts:
              - name: static-data
                mountPath: /var/www/html
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: matomo-registry-secret
          volumes:
          - name: matomo-configuration
            configMap:
              name: matomo-configuration
          - name: static-data
            emptyDir: {}
{{- end -}}
