---
{{- if .Values.matomo.cli.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo-cli
  namespace: {{.Values.namespace}}
  labels:
    app: matomo-cli
spec:
  replicas: {{.Values.matomo.cli.replicas}}
  selector:
    matchLabels:
      app: matomo-cli
  template:
    metadata:
      labels:
        app: matomo-cli
      annotations:
        kubernetes.io/change-cause: {{.Values.changeCause}}
    spec:
{{ include "matomo.init" . | nindent 6 }}
      containers:
      - name: matomo
        image: {{.Values.matomo.image}}
        {{- if .Values.matomo.cli.resources }}
        resources:
{{ toYaml .Values.matomo.cli.resources | indent 10 }}
        {{- end }}
        securityContext:
          runAsUser: {{.Values.matomo.runAsUser}}
          privileged: false
          allowPrivilegeEscalation: false
        imagePullPolicy: Always
        env:
        - name: MATOMO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.password.secretKeyRef.name }}
              key: {{ .Values.db.password.secretKeyRef.key }}
{{ include "matomo.license" . | nindent 8 }}
        command: [ 'sh' , '-c' , 'supervisord -n' ]
        volumeMounts:
          - name: static-data
            mountPath: /var/www/html
          - name: matomo-supervisor-tracker
            mountPath: /etc/supervisor.d
            readOnly: true
{{ include "matomo.images.pullSecrets" ( dict "images" (list .Values.matomo) "global" .Values.global) | nindent 6 }}
      volumes:
      - name: matomo-configuration
        configMap:
          name: matomo-configuration
      - name: static-data
        emptyDir: {}
      - name: matomo-supervisor-tracker
        configMap:
          name: matomo-supervisor-tracker
---
apiVersion: v1
kind: Service
metadata:
  name: matomo-cli
  namespace: {{.Values.namespace}}
  labels:
    app: matomo-cli
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: matomo-cli
{{- end -}}