{{- if .Values.matomo.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app: matomo-tracker
{{- if .Values.matomo.httpRoute.extralabels }}
{{ toYaml .Values.matomo.httpRoute.extralabels | indent 4 }}
{{- end }}
  name: matomo-tracker
  namespace: {{ .Values.namespace }}
{{- $annotations := .Values.matomo.tracker.httpRoute.annotations | default .Values.matomo.httpRoute.annotations }}
{{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
{{- end }}
spec:
{{- $parentRefs := .Values.matomo.tracker.httpRoute.parentRefs | default .Values.matomo.httpRoute.parentRefs }}
{{- if $parentRefs }}
  parentRefs:
    {{- toYaml $parentRefs | nindent 4 }}
{{- end }}
{{- if .Values.matomo.tracker.hostname }}
  hostnames:
    - {{ .Values.matomo.tracker.hostname | quote }}
{{- end }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /index.php
        - path:
            type: Exact
            value: /piwik.php
        - path:
            type: Exact
            value: /matomo.php
        - path:
            type: Exact
            value: /piwik.js
        - path:
            type: Exact
            value: /matomo.js
        - path:
            type: PathPrefix
            value: /js
        - path:
            type: PathPrefix
            value: /plugins/HeatmapSessionRecording
        - path:
            type: PathPrefix
            value: /plugins/Overlay/client
        - path:
            type: PathPrefix
            value: /node_modules/jquery/dist
        - path:
            type: PathPrefix
            value: /plugins/UserFeedback/lib
        - path:
            type: PathPrefix
            value: /plugins/UserFeedback/css
      backendRefs:
        {{- if .Values.matomo.tracker.loadbalancer }}
        - name: matomo-tracker-lb
          port: 80
        {{- else }}
        - name: matomo-tracker
          port: 8080
        {{- end }}
{{- end }}
