{{- if .Values.matomo.tracker.loadbalancer }}
apiVersion: v1
kind: Service
metadata:
  name: matomo-tracker-lb
spec:
  selector:
    app: matomo-tracker
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
{{- end -}}