{{- if .Values.networkPolicy.enabled }}
{{- $components := list }}
{{- if .Values.matomo.dashboard.enabled }}{{- $components = append $components "matomo-dashboard" }}{{- end }}
{{- if .Values.matomo.tracker.enabled }}{{- $components = append $components "matomo-tracker" }}{{- end }}
{{- if .Values.matomo.cli.enabled }}{{- $components = append $components "matomo-cli" }}{{- end }}
{{- if .Values.matomo.queuedTrackingMonitor.enabled }}{{- $components = append $components "matomo-queuedtracking-monitor" }}{{- end }}
{{- if .Values.matomo.queuedTrackingProcess.enabled }}{{- $components = append $components "matomo-queuedtracking-process" }}{{- end }}
{{- range $app := $components }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $app }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $app }}
spec:
  podSelector:
    matchLabels:
      app: {{ $app }}
  policyTypes:
    - Ingress
  ingress:
{{ toYaml $.Values.networkPolicy.ingress | indent 4 }}
{{- end }}
{{- end }}
