{{- if .Values.extraSecrets.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: matomo-extra-secrets
  namespace: {{.Values.namespace}}
data:
{{- if  and .Values.extraSecrets.create .Values.extraSecrets.data }}
{{- range $index, $content := .Values.extraSecrets.data }}
  {{ $index }}: |-
{{ $content | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
