changeCause: "Remove tag manager command"
namespace: matomo
nginxWorkerProcesses: 5
queuedTrackingProcess:
  numProcs: 8
matomo:
  image: registry.wklive.net:5000/dg/base-matomo:3.9.1-php7.2.18-fpm-alpine3.9-723dd7353b85922d6682e835ae1b79cabadf4a40
  runAsUser: 82
  installCommand: ./console plugin:activate ExtraTools && ./console matomo:install --install-file=/tmp/matomo/install.json --force --do-not-drop-db
  license:
    secretKeyRef:
      name: matomo-license
      key: matomo-license
  cronJobs:
    coreArchive:
      schedule: "1 1 1 1 1"
      activeDeadlineSeconds: 43200
      command: ./console core:archive --disable-scheduled-tasks
    scheduledTasks:
      schedule: "1 1 1 1 1"
      activeDeadlineSeconds: 43200
      command: ./console scheduled-tasks:run
    # swiftDbBackup:
    #   image: registry.wklive.net:5000/digitalist/k8s-db-backup:python-3.7.2-slim-stretch-master-49619e0d334ef7849658559a6086a7187178be0a
    #   schedule: "*/10 * * * *"
    #   namePrefix: matomo
    #   deleteBackupAfter: "60"
    #   openStackSecret: matomo-openstack-secret
  dashboard:
    replicas: 1
    hostname: localhost
    tls: false
    firstuser:
      username: admin
      password: admin123
      email: foo@example.com
  queuedTrackingProcess:
    replicas: 1
  tracker:
    replicas: 1
    hostname: localhost
    tls: false
nginx:
  image: registry.wklive.net:5000/digitalist/nginx:1.15.8-alpine-master-f152f040580cd163d7cdf4138d8ca897e63282c6
  runAsUser: 100
db:
  hostname: matomo-db-mysql
  hostnameSlave: matomo-db-mysql-slave
  password:
    secretKeyRef:
      name: matomo-db-mysql
      key: mysql-root-password
  name: matomo
  username: root
  prefix: matomo_