on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: build oci
        env:
          REGISTRY: "${{ secrets.REGISTRY }}"
          REG_USER: "${{ secrets.REG_USER }}"
          REG_PASS: "${{ secrets.REG_PASS }}"

        run: |
           cd charts
           helm package matomo
           helm registry login $REGISTRY -u $REG_USER -p $REG_PASS
           helm push matomo-${{ github.event.release.tag_name }}.tgz $REGISTRY



